[build]
command = "npm run build"
publish = ".next"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
NODE_OPTIONS = "--max_old_space_size=1024"

# Increase build memory limit to avoid potential memory issues
[build.processing]
skip_processing = false

# Configure Netlify Functions
[functions]
node_bundler = "esbuild"
external_node_modules = ["@node-rs/bcrypt", "next"]
included_files = ["next.config.js", ".env.local"]

# Set functions timeout appropriately
[functions.api-sitemap]
pattern = "*/api/sitemap*"
included_files = ["scripts/generate-sitemap.cjs"]
memory = 1024
timeout = 30

# Fix for Google "Page with redirect" errors by creating direct redirects
[[redirects]]
from = "http://badger3000.com/*"
to = "https://www.badger3000.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://badger3000.com/*"
to = "https://www.badger3000.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.badger3000.com/*"
to = "https://www.badger3000.com/:splat"
status = 301
force = true

# Configure specific function pattern for sitemap
[[redirects]]
from = "/api/sitemap*"
to = "/.netlify/functions/api/sitemap"
status = 200
force = true

# Set cache headers for better performance
[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Add specific headers for API routes
[[headers]]
for = "/api/*"
[headers.values]
Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"
X-Content-Type-Options = "nosniff"

# Set proper headers for sitemap files - with more specific patterns
[[headers]]
for = "/sitemap*.xml"
[headers.values]
Content-Type = "application/xml"
Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"
X-Content-Type-Options = "nosniff"

[[headers]]
for = "/server-sitemap.xml"
[headers.values]
Content-Type = "application/xml"
Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"
X-Content-Type-Options = "nosniff"

[[plugins]]
package = "@netlify/plugin-nextjs"
