[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

# Content Security Policy for forms
[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "form-action https:"
