[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

# These redirects are required for Next.js + Netlify Forms
[[redirects]]
force = true
from = "/*"
status = 200
to = "/.netlify/functions/next_static"

# Make sure Netlify serves the form detection HTML file
[[redirects]]
from = "/form-detection"
to = "/form-detection.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Content-Security-Policy = "form-action https:"
