[build]
command = "npm run build"
publish = ".next"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
NODE_ENV = "production"
NEXT_PUBLIC_SANITY_DATASET = "production"

# Increase build memory limit to avoid potential memory issues
[build.processing]
skip_processing = false

# Increase function execution timeout
[functions]
node_bundler = "esbuild"
external_node_modules = ["@node-rs/bcrypt", "next"]
included_files = ["next.config.js"]
# Increase the function timeout to 20 seconds
timeout = 20

# Handle redirects for SPA-like navigation
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
conditions = { Role = ["anonymous"] }
force = false
query = { path = ":path" }

# Handle API redirects for sitemap
[[redirects]]
from = "/server-sitemap.xml"
to = "/.netlify/functions/server/api/sitemap"
status = 200
force = true

# Set cache headers for better performance
[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Add specific headers for API routes
[[headers]]
for = "/api/*"
[headers.values]
Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"
X-Content-Type-Options = "nosniff"

# Set proper headers for sitemap files
[[headers]]
for = "/*.xml"
[headers.values]
Content-Type = "application/xml"
Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"
X-Content-Type-Options = "nosniff"

[[plugins]]
package = "@netlify/plugin-nextjs"
