export const DEFAULT_IMAGES = [
  {
    id: '1',
    source: '01.jpg',
    thumbnail: '01.jpg',
    caption: 'Whisk',
    link: 'https://whisk.com/',
    description: 'WordPress, HTML, JavaScript, Gulp, Docker, SCSS',
  },
  {
    id: '2',
    source: '02',
    thumbnail: '02.jpg',
    caption: 'Dis.co',
    link: 'https://dis.co/',
    description:
      'GatsbyJS, ReactJS, SCSS, Netlify, NodeJs, HTML, (Headless) WordPress, JSON',
  },
  {
    id: '3',
    source: '03',
    thumbnail: '03.jpg',
    caption: 'Bell',
    link: 'https://www.bellflight.com/',
    description: 'Site Core, JavaScript, HTML, JQuery, SCSS',
  },
  {
    id: '4',
    source: '04',
    thumbnail: '04.jpg',
    caption: 'Western Digital',
    link: 'https://www.westerndigital.com/',
    description: 'WordPress, HTML, Gulp, JavaScript, TailwindsJS, CSS, jQuery',
  },
  {
    id: '5',
    source: '05',
    thumbnail: '05.jpg',
    caption: 'Sony UK',
    link: 'https://www.sony.co.uk/',
    description: 'Java, Scala, Jade, JavaScript, HMTL, SCSS, jQuery, JSON ',
  },
  {
    id: '6',
    source: '06',
    thumbnail: '06.jpg',
    caption: 'Hotwire',
    link: 'https://www.hotwire.com/hotels/',
    description: 'Java, JavaScript, HTML, CSS, Google Maps API',
  },
]
