name: Latest blog posts workflow
permissions:
  contents: write
  pull-requests: write
on:
  schedule:
    # Runs every Sunday at midnight
    - cron: "0 0 * * 0"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
      NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
      NEXT_PUBLIC_AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
      SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          npm install @sanity/client feed

      - name: Update README with blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "${{ env.NEXT_PUBLIC_SITE_URL }}/api/articles-feed"
          max_post_count: 5
          template: "[$title]($url)"
          disable_sort: false

      - name: Create Pull Request if main branch is protected
        if: failure()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update README with latest blog posts
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: update-readme-blog-posts
          delete-branch: true
          title: "Update README with latest blog posts"
          body: |
            Update README with the latest blog posts from your website.

            This PR was automatically created by the GitHub Actions workflow.
          base: main
