name: Latest blog posts workflow
permissions:
  contents: write
  pull-requests: write
on:
  schedule:
    # Runs every Sunday at midnight
    - cron: "0 0 * * 0"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
      NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
      NEXT_PUBLIC_AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
      SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Execute blog post updater script
        id: update-readme
        run: node scripts/update-readme.js

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update README with latest blog posts
          title: Update README with latest blog posts
          body: |
            This PR updates the README with the latest blog posts from the API.

            Auto-generated by the blog-post-workflow GitHub Action.
          branch: update-readme-with-blog-posts
          base: master
          delete-branch: true
