name: GitHub Activity Update
on:
  schedule:
    - cron: "30 * * * *" # Runs every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with recent activity

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          GH_USERNAME: badger3000
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          COMMIT_MSG: ":zap: Update README with the recent activity"
          MAX_LINES: 5
          TARGET_FILE: README.md
          EMPTY_COMMIT_MSG: ":memo: empty commit to keep workflow active after 60 days of no activity"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
