import React from 'react'
/**
 * Implement Gatsby's SSR (Server Side Rendering) APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/ssr-apis/
 */

// You can delete this file if you're not using it
export const onRenderBody = ({ setHtmlAttributes, setHeadComponents }) => {
  setHtmlAttributes({ lang: 'en-GB' }),
    setHeadComponents([
      <link
        key="sansPro"
        rel="preload"
        href="fonts/SourceSansPro-Regular.woff2"
        as="font"
        type="font/woff2"
        crossOrigin="anonymous"
      />,
      <link
        key="sansPro"
        rel="preload"
        href="fonts/SourceSansPro-Regular.woff"
        as="font"
        type="font/woff"
        crossOrigin="anonymous"
      />,
      <link
        key="sansPro"
        rel="preload"
        href="fonts/SourceSansPro-Regular.eot"
        as="font"
        type="font/embedded-opentype"
        crossOrigin="anonymous"
      />,
      <link
        key="sansPro"
        rel="preload"
        href="fonts/SourceSansPro-Regular.ttf"
        as="font"
        type="font/truetype"
        crossOrigin="anonymous"
      />,
      <link
        key="sansPro"
        rel="preload"
        href="fonts/SourceSansPro-Regular.svg#SourceSansPro-Regular"
        as="font"
        type="font/svg"
        crossOrigin="anonymous"
      />,
      <link
        key="sansPro"
        rel="preload"
        href="fonts/SourceSansPro-Italic.eot"
        as="font"
        type="embedded-opentype"
        crossOrigin="anonymous"
      />,
      <link
        key="sansPro"
        rel="preload"
        href="fonts/SourceSansPro-Italic.woff2"
        as="font"
        type="font/woff2"
        crossOrigin="anonymous"
      />,
      <link
        key="sansPro"
        rel="preload"
        href="fonts/SourceSansPro-Italic.woff"
        as="font"
        type="font/woff"
        crossOrigin="anonymous"
      />,
      <link
        key="sansPro"
        rel="preload"
        href="fonts/SourceSansPro-Italic.ttf"
        as="font"
        type="font/truetype"
        crossOrigin="anonymous"
      />,
      <link
        key="sansPro"
        rel="preload"
        href="fonts/SourceSansPro-Italic.svg#SourceSansPro-Italic"
        as="font"
        type="font/svg"
        crossOrigin="anonymous"
      />,
    ])
}
